package/linux-pam: select libxcrypt with glibc
Fix the following build failure raised since bump of glibc to version
2.39 in commit b5680f53d60acf8ff6010082f873438a39bd5d97:

/home/autobuild/autobuild/instance-6/output-1/per-package/linux-pam/host/bin/../lib/gcc/or1k-buildroot-linux-gnu/13.2.0/../../../../or1k-buildroot-linux-gnu/bin/ld: .libs/pam_pwhistory_la-opasswd.o: in function `compare_password':
opasswd.c:(.text+0x26c): undefined reference to `crypt'

Fixes: b5680f53d60acf8ff6010082f873438a39bd5d97
 - http://autobuild.buildroot.org/results/e17911978febb7b25112940a7c40037b3f98d491

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit ef833f926b43713f23944898d1d4e64ee26f046d)
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>